$ProKeysFileName = $parentDirectory + "\keys_pro.txt"
$HomeKeysFileName = $parentDirectory + "\keys.txt"
$GetKeyByServer = $false
$IsChangeKeys = $true
$UserName = "niubaoshu"
$PD = "niubaoshu"
$ssid = "Top Prime Inc."
$password = "12345789"
$removeWIFI = $false
$currentDate = "2024-11-21"
$Version = "v0.0.2-alpha"
