$ProKeysFileName = $parentDirectory + "\keys_pro.txt"
$HomeKeysFileName = $parentDirectory + "\keys.txt"
$GetKeyByServer = $false
$IsChangeKeys = $true
$UserName = "niubaoshu"
$PD = "niubaoshu"
$ssid = "Top Prime Inc."
$password = "12345789"
#$ssid = "Tomato5G"
#$password = "9132821mlshyang"
$removeWIFI = $true
$currentDate = "2024-11-21"
$Version = "v0.0.6-alpha"
